server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx_db
    username: root
    password: root

logging:
  level:
    com.xxx: debug